### ISSUE TITLE
branding issues:  favicon showing as "ISO" blue logo and incorrect tab/window name

### ISSUE THREAD

**Issue by ReesePlews** [MetaverseStandards/metaversestandards-glossary#4]
great work everyone with getting the site up and running! thank you all!

i noticed a couple of minor items:

1) ~~i am seeing (and checking with different browsers) that the favicon is showing as the ISO logo.  please change to the MSF favicon~~

2) ~~on the tab/window name, it is showing as "index - MLTG: The Authoritative Multi-Lingual geographic information..."  please remove the "geographic information..." aspect of the title.~~

we will need to think if there is a need for any branding revisions to the site/glossary. 
it does not need to take place immediately but in the near term.

 some comments on that are:
a) the URL https://glossary.metaverse-standards.org looks good to me; if we need to change it, we need to do it at the start; we dont want to change it later, as people may be linking to our individual concepts. 

b) the MLGT or multi-lingual aspect of the site/name is a bit surprising but its ok for now. i was only thinking that MSF would have terms in English, but perhaps in the future, translations will be available for some of them.  i have no problem keeping the MLGT acronym if people like that.

c) the actual naming, we can discuss and see what the group thinks is best;  "Metaverse Standards Forum Multi-Lingual Glossary of Terms (MLGT)" will default (in spoken and written usage) to a shortened form of "Metaverse Standards Forum MLGT"; the "MLGT" acronym may be a bit new to the MSF but its simple to understand;  as a very shortened form i am not sure if this would become "MSF-MLGT" ; it is a minor issue but as we refer to the glossary moving forward we need to be uniform in our description.

again, thank you all for getting the site working!

**Comment by allcreatures** [comment]
None of the text has been approved. My goal was to get this working in the quickest way possible, so I just manually adjusted things as I saw them. Ideally, the site needs a walk through and all text/logo' adjusted.  Ideally this should not be me to update the text. The working group will need to review and send over changes, or better, submit PRs against the current text and templates :)

Favicon, forgot to update that one! Doing shortly.

**Comment by allcreatures** [comment]
Favicon is updated, but due to the caching of favicon's you most likely need to clear the data for the site in your local browser, to see the new favicon. You can view the favicon.ico file [here](https://glossary.metaverse-standards.org/favicon.ico).

**Comment by ReesePlews** [comment]
seeing the new favicon already James! thanks.

totally understand about the text/branding and that is why those items are for future discussion;

i did not see any other iso/tc211 text "hold-outs" on the site, other than that tab-name. not sure where that is happening...
can be addressed in the future.

**Comment by allcreatures** [comment]
Tab has been renamed too MLGT: The authoritative multi-lingual glossary of terms for now.

**Comment by ReesePlews** [comment]
thanks @outofcontrol, perfect for now!

i will close this issue and move the "branding" discussion to a new issue we can address later.
