### ISSUE TITLE
CI fails to trigger site rebuild

### ISSUE THREAD

**Issue by strogonoff** [MetaverseStandards/metaversestandards-glossary#7]
Logs: https://github.com/MetaverseStandards/metaversestandards-glossary/actions/runs/5748940492/job/15582794335

**Comment by ribose-jeffreylau** [comment]
I guess it's something to do with `secrets.GLOSSARIST_CI_PAT_TOKEN` not having enough privilege.

**Comment by allcreatures** [comment]
Guessing a GH Token expired. Will sort this out today. Apologies on the oversight.

**Comment by allcreatures** [comment]
@strogonoff This should be working now if I selected the correct token to regen. Please try again.

**Comment by strogonoff** [comment]
Works! Thanks James!
